<?php

namespace App\Admin\Controllers\Config;

use App\Admin\Repositories\Equip;
use Dcat\Admin\Form;
use Dcat\Admin\Grid;
use Dcat\Admin\Show;
use Dcat\Admin\Http\Controllers\AdminController;

class EquipController extends AdminController
{
    /**
     * Make a grid builder.
     *
     * @return Grid
     */
    protected function grid()
    {
        return Grid::make(new Equip(), function (Grid $grid) {
            $grid->column('id')->sortable();
            $grid->column('class');
            $grid->column('quality');
            $grid->column('type');
            $grid->column('index');
            $grid->column('equip_point');
            $grid->column('visual');
            $grid->column('rule');
            $grid->column('suit_id');
            $grid->column('suit_value');
            $grid->column('name');
            $grid->column('lv');
            $grid->column('menpai');
            $grid->column('desc');
            $grid->column('price');
            $grid->column('sale_price');
            $grid->column('max_value');
            $grid->column('fix_fail_value');
            $grid->column('max_gem');
            $grid->column('skill_id');
            $grid->column('script_id');
            $grid->column('icon');
            $grid->column('desc_type');
            $grid->column('piao_id');
            $grid->column('is_zz');
            $grid->column('is_pz');
            $grid->column('basic_phy_attack');
            $grid->column('basic_mag_attack');
            $grid->column('basic_phy_def');
            $grid->column('basic_mag_def');
            $grid->column('basic_hit');
            $grid->column('basic_miss');
            $grid->column('hp_max_value');
            $grid->column('hp_max_percent');
            $grid->column('hp_back_value');
            $grid->column('mp_max_value');
            $grid->column('mp_max_percent');
            $grid->column('mp_back_value');
            $grid->column('cold_att');
            $grid->column('cold_def');
            $grid->column('cold_keep_time');
            $grid->column('fire_att');
            $grid->column('fire_def');
            $grid->column('fire_keep_time');
            $grid->column('light_att');
            $grid->column('light_def');
            $grid->column('light_keep_time');
            $grid->column('postion_att');
            $grid->column('postion_def');
            $grid->column('postion_keep_time');
            $grid->column('def_all_percent');
            $grid->column('phy_attack');
            $grid->column('phy_attack_percent');
            $grid->column('add_phy_attack_percent');
            $grid->column('phy_def');
            $grid->column('phy_def_percent');
            $grid->column('add_phy_def_percent');
            $grid->column('miss_phy_def_percent');
            $grid->column('mag_attack');
            $grid->column('mag_attack_percent');
            $grid->column('add_mag_attack_percent');
            $grid->column('mag_def');
            $grid->column('mag_def_percent');
            $grid->column('add_mag_def_percent');
            $grid->column('miss_mag_def_percent');
            $grid->column('attach_speed');
            $grid->column('mag_cold_time');
            $grid->column('hit');
            $grid->column('miss');
            $grid->column('critical_att');
            $grid->column('ignore_percent');
            $grid->column('move_percent');
            $grid->column('attack_back');
            $grid->column('attach_cost');
            $grid->column('str');
            $grid->column('spr');
            $grid->column('con');
            $grid->column('com');
            $grid->column('dex');
            $grid->column('critical_def');
            $grid->column('qian_neng');
            $grid->column('hp_sto');
            $grid->column('mp_sto');
            $grid->column('add_skill_lv');
            $grid->column('add_all_skill_lv');
            $grid->column('spe_skill_rate');
            $grid->column('Resist_cold_def');
            $grid->column('Resist_fire_def');
            $grid->column('Resist_light_def');
            $grid->column('Resist_postion_def');
            $grid->column('quality_rule');
            $grid->column('begin_attr');
            $grid->column('attr_min');
            $grid->column('attr_max');
            $grid->column('zz_min');
            $grid->column('zz_max');
            $grid->column('level_up_id');
            $grid->column('bag');
            $grid->column('box');
            $grid->column('is_boradcast');
            $grid->column('float_space');
            $grid->column('quality_level');
        
            $grid->filter(function (Grid\Filter $filter) {
                $filter->equal('id');
        
            });
        });
    }

    /**
     * Make a show builder.
     *
     * @param mixed $id
     *
     * @return Show
     */
    protected function detail($id)
    {
        return Show::make($id, new Equip(), function (Show $show) {
            $show->field('id');
            $show->field('class');
            $show->field('quality');
            $show->field('type');
            $show->field('index');
            $show->field('equip_point');
            $show->field('visual');
            $show->field('rule');
            $show->field('suit_id');
            $show->field('suit_value');
            $show->field('name');
            $show->field('lv');
            $show->field('menpai');
            $show->field('desc');
            $show->field('price');
            $show->field('sale_price');
            $show->field('max_value');
            $show->field('fix_fail_value');
            $show->field('max_gem');
            $show->field('skill_id');
            $show->field('script_id');
            $show->field('icon');
            $show->field('desc_type');
            $show->field('piao_id');
            $show->field('is_zz');
            $show->field('is_pz');
            $show->field('basic_phy_attack');
            $show->field('basic_mag_attack');
            $show->field('basic_phy_def');
            $show->field('basic_mag_def');
            $show->field('basic_hit');
            $show->field('basic_miss');
            $show->field('hp_max_value');
            $show->field('hp_max_percent');
            $show->field('hp_back_value');
            $show->field('mp_max_value');
            $show->field('mp_max_percent');
            $show->field('mp_back_value');
            $show->field('cold_att');
            $show->field('cold_def');
            $show->field('cold_keep_time');
            $show->field('fire_att');
            $show->field('fire_def');
            $show->field('fire_keep_time');
            $show->field('light_att');
            $show->field('light_def');
            $show->field('light_keep_time');
            $show->field('postion_att');
            $show->field('postion_def');
            $show->field('postion_keep_time');
            $show->field('def_all_percent');
            $show->field('phy_attack');
            $show->field('phy_attack_percent');
            $show->field('add_phy_attack_percent');
            $show->field('phy_def');
            $show->field('phy_def_percent');
            $show->field('add_phy_def_percent');
            $show->field('miss_phy_def_percent');
            $show->field('mag_attack');
            $show->field('mag_attack_percent');
            $show->field('add_mag_attack_percent');
            $show->field('mag_def');
            $show->field('mag_def_percent');
            $show->field('add_mag_def_percent');
            $show->field('miss_mag_def_percent');
            $show->field('attach_speed');
            $show->field('mag_cold_time');
            $show->field('hit');
            $show->field('miss');
            $show->field('critical_att');
            $show->field('ignore_percent');
            $show->field('move_percent');
            $show->field('attack_back');
            $show->field('attach_cost');
            $show->field('str');
            $show->field('spr');
            $show->field('con');
            $show->field('com');
            $show->field('dex');
            $show->field('critical_def');
            $show->field('qian_neng');
            $show->field('hp_sto');
            $show->field('mp_sto');
            $show->field('add_skill_lv');
            $show->field('add_all_skill_lv');
            $show->field('spe_skill_rate');
            $show->field('Resist_cold_def');
            $show->field('Resist_fire_def');
            $show->field('Resist_light_def');
            $show->field('Resist_postion_def');
            $show->field('quality_rule');
            $show->field('begin_attr');
            $show->field('attr_min');
            $show->field('attr_max');
            $show->field('zz_min');
            $show->field('zz_max');
            $show->field('level_up_id');
            $show->field('bag');
            $show->field('box');
            $show->field('is_boradcast');
            $show->field('float_space');
            $show->field('quality_level');
        });
    }

    /**
     * Make a form builder.
     *
     * @return Form
     */
    protected function form()
    {
        return Form::make(new Equip(), function (Form $form) {
            $form->display('id');
            $form->text('class');
            $form->text('quality');
            $form->text('type');
            $form->text('index');
            $form->text('equip_point');
            $form->text('visual');
            $form->text('rule');
            $form->text('suit_id');
            $form->text('suit_value');
            $form->text('name');
            $form->text('lv');
            $form->text('menpai');
            $form->text('desc');
            $form->text('price');
            $form->text('sale_price');
            $form->text('max_value');
            $form->text('fix_fail_value');
            $form->text('max_gem');
            $form->text('skill_id');
            $form->text('script_id');
            $form->text('icon');
            $form->text('desc_type');
            $form->text('piao_id');
            $form->text('is_zz');
            $form->text('is_pz');
            $form->text('basic_phy_attack');
            $form->text('basic_mag_attack');
            $form->text('basic_phy_def');
            $form->text('basic_mag_def');
            $form->text('basic_hit');
            $form->text('basic_miss');
            $form->text('hp_max_value');
            $form->text('hp_max_percent');
            $form->text('hp_back_value');
            $form->text('mp_max_value');
            $form->text('mp_max_percent');
            $form->text('mp_back_value');
            $form->text('cold_att');
            $form->text('cold_def');
            $form->text('cold_keep_time');
            $form->text('fire_att');
            $form->text('fire_def');
            $form->text('fire_keep_time');
            $form->text('light_att');
            $form->text('light_def');
            $form->text('light_keep_time');
            $form->text('postion_att');
            $form->text('postion_def');
            $form->text('postion_keep_time');
            $form->text('def_all_percent');
            $form->text('phy_attack');
            $form->text('phy_attack_percent');
            $form->text('add_phy_attack_percent');
            $form->text('phy_def');
            $form->text('phy_def_percent');
            $form->text('add_phy_def_percent');
            $form->text('miss_phy_def_percent');
            $form->text('mag_attack');
            $form->text('mag_attack_percent');
            $form->text('add_mag_attack_percent');
            $form->text('mag_def');
            $form->text('mag_def_percent');
            $form->text('add_mag_def_percent');
            $form->text('miss_mag_def_percent');
            $form->text('attach_speed');
            $form->text('mag_cold_time');
            $form->text('hit');
            $form->text('miss');
            $form->text('critical_att');
            $form->text('ignore_percent');
            $form->text('move_percent');
            $form->text('attack_back');
            $form->text('attach_cost');
            $form->text('str');
            $form->text('spr');
            $form->text('con');
            $form->text('com');
            $form->text('dex');
            $form->text('critical_def');
            $form->text('qian_neng');
            $form->text('hp_sto');
            $form->text('mp_sto');
            $form->text('add_skill_lv');
            $form->text('add_all_skill_lv');
            $form->text('spe_skill_rate');
            $form->text('Resist_cold_def');
            $form->text('Resist_fire_def');
            $form->text('Resist_light_def');
            $form->text('Resist_postion_def');
            $form->text('quality_rule');
            $form->text('begin_attr');
            $form->text('attr_min');
            $form->text('attr_max');
            $form->text('zz_min');
            $form->text('zz_max');
            $form->text('level_up_id');
            $form->text('bag');
            $form->text('box');
            $form->text('is_boradcast');
            $form->text('float_space');
            $form->text('quality_level');
        });
    }
}
